# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_picture', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
