# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicData',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('topic_key', models.IntegerField()),
                ('data_entry', models.TextField()),
                ('platform', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('sentiment_x', models.DecimalField(decimal_places=5, max_digits=7)),
                ('sentiment_y', models.DecimalField(decimal_places=5, max_digits=7)),
                ('created_by', models.CharField(max_length=255)),
                ('coordinates', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('likes_fav', models.IntegerField(blank=True, null=True)),
                ('shares_retweet', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'topic_data',
                'managed': False,
                'db_tablespace': 'test_sentiment',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('event', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'logs',
                'db_tablespace': 'default',
            },
        ),
        migrations.CreateModel(
            name='TopicKeys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key_val', models.CharField(max_length=255)),
                ('topic_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'topic_keys',
                'db_tablespace': 'test_sentiment',
            },
        ),
    ]
